Game 57
Nepommuck/SusGameFrontend pull request #6
Opened 2024-05-23 15:35 UTC by uqsz

https://student-team-itzvvb1dm3zv.atlassian.net/browse/GAME-57

2024-06-01 14:15 UTC, Nepommuck requested changes
Bardzo fajnie, że aktualizujesz na bieżąco front, do tego jak implementacja tego grafu na serwerze ma wyglądać. Ja tak szczerze nie patrzyłem za bardzo na to, co się dzieje w tamtym repo

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/game/util.kt
> +data class PlayerId(val value: Int?)
Myślę, że można spokojnie przenieść te obie klasy do plików `Lobby.kt` i `Player.kt`

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/game/util.kt
> +data class PlayerId(val value: Int?)
Nie podoba mi się za bardzo to `Int?`. Jeśli musi być opcjonalne, to przenieś to wyżej, żeby `Player` miał `id: PlayerId?`

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/ServerMapState.kt
> +// !!! this file is for delete, content from here went to model.graph
Możesz usunąć cały plik

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/game/Lobby.kt
> +    val gamePin: String?, // probably not safe here, should be hidden in the future
Hmm widzę, że to i tak na razie jest nieużywane, więc można usunąć to `gamePin`. Pewnie w przyszłości tak czy tak będzie szło zapytanie do serwera z podanym hasłem i będzie zwracane jakieś `401 UNAUTHORIZED`

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/Player.kt
> +    var id: PlayerId = PlayerId(null),
Hmm, tak szczerze to jakbym sam to pisał, to zrobiłbym niemutowalne i bez wartości opcjonalnych (zobacz też komentarz do samego `PlayerId`). Gdyby była faktycznie potrzeba, że graczom zmienia się to id (bo np. dołączają do gry), to zrobiłbym osobną klasę typu `PlayerOutsideLobby(val name: String)`

NATOMIAST

Jak masz jakąś taką koncepcję, że będzie to działać, to myślę że możesz na razie zostawić. Najwyżej sam to kiedyś zmienię jakby mi bardzo przeszkadzało

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/game/Lobby.kt
> +        player.id = newPlayerId
Kurcze cała ta logika z `freePlayerId` i inkrementacją tego ma sens w mockowej implementacji (`MockLobbiesProvider`), natomiast chciałbym, żeby klasy, które są używane przez sam interfejs były już pozbawione takich rzeczy.

Widzę, że te metody `addPlayer()` i `kickPlayer()` są obecnie używane tylko w mockowej implementacji, więc powino się łatwo przenieść logikę tego nadawania `PlayerId` właśnie tam

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/providers/interfaces/LobbiesProvider.kt
> +    fun leave(lobbyId: LobbyId, playerId: PlayerId): CompletableFuture<Unit>
Teraz mi się przypomniało, że te 2 metody będą prawdopodobnie i tak do wyrzucenia w przyszłości, bo dołączenie do gry na serwerze jest (as far as I know) realizowane poprzez stworzenie połączenia z web socketem, a nie jako zapytanie REST.

Na razie zostaw jak jest

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/providers/interfaces/LobbiesProvider.kt
> +    fun createCustomLobbies() // this function is only for testing, it shows logic behind creating new lobbies
Tip: Jeśli tworzy komentarze do funkcji tworzy się w ten sposób:
```
    /**
     * This function is only for testing, it shows logic behind creating new lobbies
     */
    fun createCustomLobbies()
``` 

to IDE będzie je wyświetlać po najechaniu

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/providers/interfaces/ServerMapProvider.kt
> +    fun createCustomMapState()// this function is only for testing, it shows logic behind creating game map
To, co wyżej odnośnie komentarzy do metod

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/providers/interfaces/ServerMapProvider.kt
>  interface ServerMapProvider {
To pewnie też trzeba będzie docelowo rozwiązać zupełnie inaczej, bo (as far as I know) serwer będzie co określony czas przesyłał przez socket nową wersję stanu rozgrywki i trzeba będzie to jakoś aktualizować na froncie

Na razie może zostać jak jest

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/providers/mock/MockLobbiesProvider.kt
> +    private var currentLobbies: MutableMap<LobbyId, Lobby> = mutableMapOf()
Bardzo fajnie, mutowalność przesunięta do wnętrza implementacji Mockowej

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/providers/mock/MockLobbiesProvider.kt
> +    override fun createCustomLobbies() {
Hmm z tego co widzę, ta metoda jest używana tylko raz (na początku przy stworzeniu tego providera). Proponuję:
1. Przenieść to wszystko do konstruktora (`init { ... }` w Kotlinie)
2. Wyrzucić `fun createCustomLobbies()` z interfejsu

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/providers/mock/MockServerMapProvider.kt
> +    override fun createCustomMapState() {
Analogicznie jak przy `MockLobbiesProvider#createCustomLobbies` chyba można przenieść do konstruktora i wyrzucić z interfejsu

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/graph/Graph.kt
> +class Graph(
Może by to jakoś zrename'ować, żeby było wiadomo, że jest to graf rozgrywki, a nie jakaś abstrakcyjna struktura danych

Moje propozycje: `GameGraph`, `GameGraphState`, `GameMap`, `ServerGraph`,  `ServerMap` itp.

Wybierz proszę to, co twoim zdaniem najbardziej pasuje

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/graph/Graph.kt
> +    val edgeMap: MutableMap<Int, Edge>,
Personalnie nazwałbym to po prostu `nodes` i `edges`, bo to że to jest mapa to widać zawsze po typie (`crtl + q`). Jest to kwestia gustu, więc zrób jak uważasz

2024-06-01 14:15 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/graph/Graph.kt
> +    }
I tutaj też myślę, że docelowo przerobimy tę klasę na w pełni niemutowalną, bo po prostu co jakiś czas od serwera będzie szedł obecny stan rozgrywki, który na froncie będziemy po prostu akceptować jako faktyczny

Na razie zostaw, bo do tego połączenia socketowego i w pełni działającego serwera jeszcze nam trochę brakuje

2024-06-02 16:01 UTC, uqsz commented on app/src/main/java/edu/agh/susgame/front/model/Player.kt
> +    var id: PlayerId = PlayerId(null),
na ten moment żeby pójść dalej z implementacją mapy potrzebuję trzymać "lokalny" identyfikator dla gracza podczas rozgrywki i nadaje go przy wejściu do lobby i usuwam po wyjściu

tutaj jak teraz myślę dobrze będzie zaimplementować identyfikator globalny i lokalny, globalny byłby nadawany przy odpalaniu aplikacji i nawiązywaniu łączności z serwerem, byłby niemutowalny i używany do  administracyjnych rzeczy, lokalny zaś przy wchodzeniu do lobby i używany stricte pod mechanikę gry, 

intuicyjnie uniezależnienie tych dwóch rzeczy byłoby korzystne, co myślisz?

2024-06-02 16:19 UTC, uqsz commented on app/src/main/java/edu/agh/susgame/front/providers/interfaces/LobbiesProvider.kt
> +    fun createCustomLobbies() // this function is only for testing, it shows logic behind creating new lobbies
bardzo fajny feature, będę używał

2024-06-02 16:32 UTC, uqsz commented on app/src/main/java/edu/agh/susgame/front/model/graph/Graph.kt
> +class Graph(
słusznie, GameGraph bardzo fajny

2024-06-02 16:35 UTC, uqsz commented on app/src/main/java/edu/agh/susgame/front/model/graph/Graph.kt
> +    val edgeMap: MutableMap<Int, Edge>,
racja, nie ma co powielać informacji, zresztą Map w kontekście całości jest trochę mylące, zmieniam na `nodes` i `edges`

2024-06-02 17:05 UTC, uqsz commented on app/src/main/java/edu/agh/susgame/front/model/game/Lobby.kt
> +        player.id = newPlayerId
przeniosłem wszystko do implementacji mocka, kwestia nadawania graczom id napewno się zmieni, narazie potrzebuję jakiegokolwiek mechanizmu zeby moc implementowac mape

2024-06-02 20:45 UTC, Nepommuck commented on app/src/main/java/edu/agh/susgame/front/model/Player.kt
> +    var id: PlayerId = PlayerId(null),
Brzmi bardzo spoko. Możemy faktycznie tak zrobić w przyszłości

2024-06-02 20:48 UTC, Nepommuck approved these changes

2024-06-02 21:27 UTC, merged